export const USER_ACTIONS = {
  REFRESH_USER: "REFRESH_USER",
  SET_ID: "SET_ID",
  LOAD_RESULT: "LOAD_RESULT",
  SET_LOADING: "SET_LOADING",
  LOAD_STATUS: "LOAD_STATUS",
  LOADING_STATUS: "LOADING_STATUS",
  LOAD_INFO_USER: "LOAD_INFO_USER",
  SET_FILTERS: "SET_FILTERS",
};
